on:
  workflow_dispatch:

jobs:
  image-id-step:
    runs-on: ubuntu-latest
    name: Get Image ID
    steps:
      - name: Image ID
        id: image-id
        uses: s3vt/docker-image-id@v1.0.0
        with:
          image_name: "s3vt/java:17"
      - name: Print the image ID
        run: echo "Image ID is ${{ steps.image-id.outputs.image_id }}"
